# Generated by Django 6.0.7 on 2026-09-02 23:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tablon_app', '0002_auto_20260822_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_aka', models.CharField(default='Anónimo', max_length=20)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateField(default=django.utils.timezone.localdate)),
                ('hora_publicacion', models.TimeField(default=django.utils.timezone.localtime)),
                ('archivo_img', models.ImageField(blank=True, null=True, upload_to='imgs')),
                ('sub_comentario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts_app.comentario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_aka', models.CharField(default='Anónimo', max_length=20)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateField(default=django.utils.timezone.localdate)),
                ('hora_publicacion', models.TimeField(default=django.utils.timezone.localtime)),
                ('archivo_img', models.ImageField(blank=True, null=True, upload_to='imgs')),
                ('titulo', models.CharField(max_length=60)),
                ('tablon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablon_app.tablon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enlace', models.URLField()),
                ('comentario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts_app.comentario')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts_app.post')),
            ],
        ),
        migrations.AddField(
            model_name='comentario',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts_app.post'),
        ),
    ]
