# Generated by Django 6.0.7 on 2026-08-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0002_comentario_sub_comentario_enlaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='op_aka',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
