# Generated by Django 6.0.7 on 2026-08-26 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0003_post_op_aka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='sub_comentario',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts_app.comentario'),
        ),
    ]
