# Generated by Django 6.0.7 on 2026-08-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0004_comentario_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='archivo_img',
            field=models.ImageField(null=True, upload_to='imgs'),
        ),
    ]
