# Generated by Django 6.0.7 on 2026-08-27 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0004_alter_comentario_sub_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='sub_comentario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts_app.comentario'),
        ),
        migrations.AlterField(
            model_name='post',
            name='op_aka',
            field=models.CharField(default='Anónimo', max_length=20),
        ),
    ]
