# Generated by Django 6.0.7 on 2026-08-29 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0005_alter_comentario_sub_comentario_alter_post_op_aka'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enlaces',
            new_name='Enlace',
        ),
    ]
