; Establece el modulo de configuración del proyecto ;

; Modulos ;
; settings -> Módulo de configuración por defecto
; gun -> Módulo de configuración funcional para gunicorn
; prod -> Módulo de configuración para despliegue/producción

[SETTING_FILE]
FILE = gun
; FILE = settings
; FILE = prod